dist: trusty
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
jobs:
  include:
    - stage: common
      name: "Verify common files are consistent"
      language: javascript
      # Only check on pull requests to master
      if: branch = master AND type = pull_request
      script:
        - git remote add -f b https://github.com/w3c/json-ld-wg.git
        - git remote update
        - git diff --exit-code remotes/b/master -- common
    - stage: examples
      name: "Verify examples are consistent"
      language: ruby
      rvm: 2.6
      script: "bundle exec rake test"
    - stage: links
      name: "Check internal links and HTML"
      sudo: required
      services:
        - docker
      # Because (alas) rawgit is end of life, we'll run this only on the master branch.
      if: branch = master
      language: ruby
      rvm: 2.6
      script:
        - docker pull stupchiy/checklink
        - docker run -it stupchiy/checklink -b -X '(http|https|mailto):' "https://labs.w3.org/spec-generator/?type=respec&url=https://raw.githack.com/w3c/json-ld-streaming/${TRAVIS_BRANCH}/index.html?specStatus=WG-NOTE&shortName=json-ld11-streaming"
        - bundle exec rake check_html
    - stage: echidna
      name: "Echidna Publication"
      language: javascript
      # Only on push to "publications" branch
      if: branch = publications AND type = push
      env:
        - URL="https://w3c.github.io/json-ld-streaming/ECHIDNA"
        - DECISION="https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-17-json-ld#resolution4"
        - secure: "m9wXefuO1A2N0rmTgdXezmdI9xdPZhbEe2G3hfOn4UPt/3N/1xxzxUW96tIv/DvYOH/xx1/DdYAzp+4SMni9nkVTV5YhL3wRdME3X1ett9tcpk7u8iFF2APImMwTFGRBApc9mu49u2EV+clWuw2o8BrHdExjSsKlE1/855zzKTGiVdKly0hV7KWVV5o+F1jg0X0QaDH3N4tx+qRrzT2nRm2QT+Mrsan3ZZnhNa6xbXb7jwgbqChdShCQ9QpRASYTfOISiKQPxjQuVO3ktDhj1B8xGSTojJx5vIl9h38JmBszRbchyBWQoba78QC76SmWUFvj67vEDVc18M/3rsy1lSyMKyADPq8iJHx0LSP8y7n3D9l6tMRg4xSDNhDewnnhomuRq/0dcQqDs1O88WISnRuR6siOzyFuQrwz4cqK1ejqy3E9ZVY3/Vjkmz0fH+S0R30R29KgNqrzW+AzqnIemAi/qypbJkNG1aKkrvWHBPQksaRJuJ36gsZcX9gLus6LoGic+iwGQlFQnxUxPIzE5kj1wATXwHX/y1uR84wzhuzM0bGd3QtRQNLoqFYBOuRN2buoTsfdJxaQx0eeh/F1X+xiFkc3vGiRxaGZJ8HUT6nxR9rl7qeLVtwfVhNnN+s/AnBw8U76pBAOfuKH8kwUxbuLOPPqmp4xyfIAkYSgeYQ="
      script:
        - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
